/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Exercise': RouteRecordInfo<'/Exercise', '/Exercise', Record<never, never>, Record<never, never>>,
    '/Log': RouteRecordInfo<'/Log', '/Log', Record<never, never>, Record<never, never>>,
    '/Settings': RouteRecordInfo<'/Settings', '/Settings', Record<never, never>, Record<never, never>>,
    '/Workout': RouteRecordInfo<'/Workout', '/Workout', Record<never, never>, Record<never, never>>,
    '/Workouts': RouteRecordInfo<'/Workouts', '/Workouts', Record<never, never>, Record<never, never>>,
  }
}
